window.FRONTERA_SEARCH_INDEX = [
  {"title":"Home","url":"index.html","text":"home overview"},
  {"title":"AK-47","url":"items/frontera_ak_47.html","text":"frontera:ak_47 frontera:ak_47 minecraft:iron_ingot frontera:weapons/ak47 <!i><gold>AK-47 <!i><gray>An assault rifle"},
  {"title":"Furnace","url":"items/frontera_furnace.html","text":"frontera:furnace frontera:furnace minecraft:furnace minecraft:furnace <gold>Furnace <gray>A bigger furnace"},
  {"title":"Ingot mall","url":"items/frontera_ingot_mall.html","text":"frontera:ingot_mall frontera:ingot_mall minecraft:clay minecraft:clay <!i><gold>Ingot mall <gray>A mall used to form ingots from molten ingots"},
  {"title":"Iron Ingot","url":"items/frontera_iron_ingot.html","text":"frontera:iron_ingot frontera:iron_ingot minecraft:iron_ingot minecraft:iron_ingot <gold>Iron Ingot <gray>Smelted from iron ore."},
  {"title":"Sieve","url":"items/frontera_sieve.html","text":"frontera:sieve frontera:sieve minecraft:diamond_hoe minecraft:diamond_hoe <!i><gold>Sieve <gray>Used to sieve items using water"},
  {"title":"Super Crafter","url":"items/frontera_super_crafter.html","text":"frontera:super_crafter frontera:super_crafter minecraft:crafting_table minecraft:crafting_table <!i><gold>Super Crafter <!i><gray>A bigger crafter"},
  {"title":"Wooden Carriage","url":"items/frontera_wooden_carriage_chest.html","text":"frontera:wooden_carriage_chest frontera:wooden_carriage_chest minecraft:stick frontera:vehicles/wooden_carriage <!i><gold>Wooden Carriage <!i><gray>A wooden carriage <!i><gray>Can be used to travel or transport goods <!i><gray>Has a chest with 54 slots"},
  {"title":"Wooden Carriage","url":"items/frontera_wooden_carriage_empty.html","text":"frontera:wooden_carriage_empty frontera:wooden_carriage_empty minecraft:stick frontera:vehicles/wooden_carriage <!i><gold>Wooden Carriage <!i><gray>A wooden carriage <!i><gray>Can be used to travel or transport goods"},
  {"title":"Wooden Carriage","url":"items/frontera_wooden_carriage_hay_bale.html","text":"frontera:wooden_carriage_hay_bale frontera:wooden_carriage_hay_bale minecraft:stick frontera:vehicles/wooden_carriage <!i><gold>Wooden Carriage <!i><gray>A wooden carriage <!i><gray>Can be used to travel or transport goods <!i><gray>Can store haybales and wheat"},
  {"title":"Wooden Wheel","url":"items/frontera_wooden_wheel.html","text":"frontera:wooden_wheel frontera:wooden_wheel minecraft:stick frontera:vehicles/wheels/wooden_wheel <gold>Wooden Wheel <gray>Can be used to craft a wooden carriage"},
  {"title":"Items","url":"items/index.html","text":"items list"},
  {"title":"frontera:hay","url":"tags/frontera_hay.html","text":"minecraft:wheat minecraft:hay_block"},
  {"title":"frontera:medium_burning","url":"tags/frontera_medium_burning.html","text":"minecraft:coal_block"},
  {"title":"frontera:short_burning","url":"tags/frontera_short_burning.html","text":"minecraft:coal minecraft:charcoal"},
  {"title":"Tags","url":"tags/index.html","text":"tags list"},
  {"title":"ak47","url":"recipes/ak47.html","text":"minecraft:diamond frontera:ak_47 shapeless tools "},
  {"title":"furnace","url":"recipes/furnace.html","text":"minecraft:cobblestone minecraft:furnace frontera:furnace shaped machines "},
  {"title":"ingot_mall","url":"recipes/ingot_mall.html","text":"minecraft:brick minecraft:clay frontera:ingot_mall shaped tools "},
  {"title":"sieve","url":"recipes/sieve.html","text":"minecraft:paper minecraft:stick frontera:sieve shaped tools "},
  {"title":"Default Recipes","url":"recipes/index.html","text":"recipes list"},
  {"title":"furnace","url":"machines/furnace/index.html","text":"XXXXXXXXX XIIIXOOOX XIIIPOOOX XIIIXOOOX XXXXXXXXX SINGLE_BLOCK minecraft:furnace"},
  {"title":"iron_ingot (furnace)","url":"machines/furnace/iron_ingot.html","text":"minecraft:iron_ore frontera:iron_ingot shapeless ores furnace"},
  {"title":"big (furnace fuel)","url":"machines/furnace/big.html","text":"minecraft:lava_bucket minecraft:bucket shapeless burning furnace"},
  {"title":"medium (furnace fuel)","url":"machines/furnace/medium.html","text":"#frontera:medium_burning  shapeless burning furnace"},
  {"title":"small (furnace fuel)","url":"machines/furnace/small.html","text":"#frontera:short_burning  shapeless burning furnace"},
  {"title":"sieve","url":"machines/sieve/index.html","text":"XXXXXXXXX XIIIXOOOX XIIIPOOOX XIIIXOOOX XXXXXXXXX SINGLE_BLOCK minecraft:furnace"},
  {"title":"iron_nugget (sieve)","url":"machines/sieve/iron_nugget.html","text":"minecraft:gravel minecraft:water minecraft:iron_nugget shapeless ores sieve"},
  {"title":"super_crafter","url":"machines/super_crafter/index.html","text":"IIIIIXXXX IIIIIXOOO IIIIIPOOO IIIIIXOOO IIIIIXXXX SINGLE_BLOCK minecraft:crafting_table"},
  {"title":"ak47 (super_crafter)","url":"machines/super_crafter/ak47.html","text":"minecraft:diamond frontera:ak_47 shapeless tools super_crafter"},
  {"title":"furnace (super_crafter)","url":"machines/super_crafter/furnace.html","text":"minecraft:cobblestone minecraft:furnace frontera:furnace shaped machines super_crafter"},
  {"title":"wooden_carriage (super_crafter)","url":"machines/super_crafter/wooden_carriage.html","text":"frontera:wooden_wheel minecraft:oak_planks minecraft:oak_log frontera:wooden_carriage_empty shaped vehicles super_crafter"},
  {"title":"wooden_carriage_chest (super_crafter)","url":"machines/super_crafter/wooden_carriage_chest.html","text":"frontera:wooden_carriage_empty minecraft:chest frontera:wooden_carriage_chest shaped vehicles super_crafter"},
  {"title":"wooden_carriage_hay_bale (super_crafter)","url":"machines/super_crafter/wooden_carriage_hay_bale.html","text":"frontera:wooden_carriage_empty minecraft:barrel minecraft:wheat frontera:wooden_carriage_hay_bale shaped vehicles super_crafter"},
  {"title":"wooden_carriage_un_chest (super_crafter)","url":"machines/super_crafter/wooden_carriage_un_chest.html","text":"frontera:wooden_carriage_chest frontera:wooden_carriage_empty minecraft:chest shapeless vehicles super_crafter"},
  {"title":"wooden_carriage_un_hay_bale (super_crafter)","url":"machines/super_crafter/wooden_carriage_un_hay_bale.html","text":"frontera:wooden_carriage_hay_bale frontera:wooden_carriage_empty minecraft:barrel minecraft:wheat shapeless vehicles super_crafter"},
  {"title":"wooden_wheel (super_crafter)","url":"machines/super_crafter/wooden_wheel.html","text":"minecraft:stick minecraft:oak_planks minecraft:oak_log frontera:wooden_wheel shaped wheels super_crafter"},
  {"title":"super_smelter","url":"machines/super_smelter/index.html","text":"XXXXXXXXX XFIIIXOOX XFIIIPOOX XFIIIXOOX XXXXXXXXX MULTI_BLOCK minecraft:cobblestone minecraft:furnace minecraft:glass"},
  {"title":"iron_ingot (super_smelter)","url":"machines/super_smelter/iron_ingot.html","text":"frontera:liquid_iron frontera:ingot_mall minecraft:iron_ingot frontera:ingot_mall shapeless ores super_smelter"},
  {"title":"molten_iron (super_smelter)","url":"machines/super_smelter/molten_iron.html","text":"minecraft:iron_nugget frontera:liquid_iron shapeless ores super_smelter"},
  {"title":"big (super_smelter fuel)","url":"machines/super_smelter/big.html","text":"minecraft:lava_bucket minecraft:bucket shapeless burning super_smelter"},
  {"title":"medium (super_smelter fuel)","url":"machines/super_smelter/medium.html","text":"#frontera:medium_burning  shapeless burning super_smelter"},
  {"title":"small (super_smelter fuel)","url":"machines/super_smelter/small.html","text":"#frontera:short_burning  shapeless burning super_smelter"},
  {"title":"tank","url":"machines/tank/index.html","text":"XXXXXXXXX XIIIFOOOX XIIIFOOOX XIIIFOOOX XXXXPXXXX MULTI_BLOCK minecraft:glass minecraft:cauldron"},
  {"title":"lava_in (tank)","url":"machines/tank/lava_in.html","text":"minecraft:lava_bucket minecraft:lava minecraft:bucket shapeless ores tank"},
  {"title":"lava_out (tank)","url":"machines/tank/lava_out.html","text":"minecraft:lava minecraft:bucket minecraft:lava_bucket shapeless ores tank"},
  {"title":"milk_in (tank)","url":"machines/tank/milk_in.html","text":"minecraft:milk_bucket minecraft:milk minecraft:bucket shapeless ores tank"},
  {"title":"milk_out (tank)","url":"machines/tank/milk_out.html","text":"minecraft:milk minecraft:bucket minecraft:milk_bucket shapeless ores tank"},
  {"title":"water_in (tank)","url":"machines/tank/water_in.html","text":"minecraft:water_bucket minecraft:water minecraft:bucket shapeless ores tank"},
  {"title":"water_out (tank)","url":"machines/tank/water_out.html","text":"minecraft:water minecraft:bucket minecraft:water_bucket shapeless ores tank"},
  {"title":"water_catcher","url":"machines/water_catcher/index.html","text":"XXXXXXXXX XIIIFOOOX XIIIFOOOX XIIIFOOOX XXXXPXXXX MULTI_BLOCK minecraft:oak_planks minecraft:cauldron"},
  {"title":"passive_water_in (water_catcher)","url":"machines/water_catcher/passive_water_in.html","text":"world:isHighHumidity minecraft:water shapeless ores water_catcher"},
  {"title":"rain_water_in (water_catcher)","url":"machines/water_catcher/rain_water_in.html","text":"world:isRaining minecraft:water shapeless ores water_catcher"},
  {"title":"water_in (water_catcher)","url":"machines/water_catcher/water_in.html","text":"minecraft:water_bucket minecraft:water minecraft:bucket shapeless ores water_catcher"},
  {"title":"water_out (water_catcher)","url":"machines/water_catcher/water_out.html","text":"minecraft:water minecraft:bucket minecraft:water_bucket shapeless ores water_catcher"},
  {"title":"Machines","url":"machines/index.html","text":"machines list"},
  {"title":"simple_car","url":"vehicles/simple_car.html","text":"simple_car gg.frontera.modules.vehiclemodule.vehicle.controller.NormalVehicleController null Self powered vehicle seats 4"},
  {"title":"wooden_canoe","url":"vehicles/wooden_canoe.html","text":"wooden_canoe gg.frontera.modules.vehiclemodule.vehicle.controller.CanoeVehicleController null Self powered boat seats 3"},
  {"title":"wooden_carriage_chest","url":"vehicles/wooden_carriage_chest.html","text":"wooden_carriage_chest gg.frontera.modules.vehiclemodule.vehicle.controller.HorsePulledVehicleController null Horse pulled vehicle seats 2"},
  {"title":"wooden_carriage_empty","url":"vehicles/wooden_carriage_empty.html","text":"wooden_carriage_empty gg.frontera.modules.vehiclemodule.vehicle.controller.HorsePulledVehicleController null Horse pulled vehicle seats 2"},
  {"title":"wooden_carriage_hay_bale","url":"vehicles/wooden_carriage_hay_bale.html","text":"wooden_carriage_hay_bale gg.frontera.modules.vehiclemodule.vehicle.controller.HorsePulledVehicleController #frontera:hay Horse pulled vehicle seats 2"},
  {"title":"Vehicles","url":"vehicles/index.html","text":"vehicles list"},
  {"title":"frontera:medium_burning usage","url":"uses/_frontera_medium_burning.html","text":"#frontera:medium_burning usage recipe where used produced by"},
  {"title":"frontera:short_burning usage","url":"uses/_frontera_short_burning.html","text":"#frontera:short_burning usage recipe where used produced by"},
  {"title":"frontera:ak_47 usage","url":"uses/frontera_ak_47.html","text":"frontera:ak_47 usage recipe where used produced by"},
  {"title":"frontera:furnace usage","url":"uses/frontera_furnace.html","text":"frontera:furnace usage recipe where used produced by"},
  {"title":"frontera:ingot_mall usage","url":"uses/frontera_ingot_mall.html","text":"frontera:ingot_mall usage recipe where used produced by"},
  {"title":"frontera:iron_ingot usage","url":"uses/frontera_iron_ingot.html","text":"frontera:iron_ingot usage recipe where used produced by"},
  {"title":"frontera:liquid_iron usage","url":"uses/frontera_liquid_iron.html","text":"frontera:liquid_iron usage recipe where used produced by"},
  {"title":"frontera:sieve usage","url":"uses/frontera_sieve.html","text":"frontera:sieve usage recipe where used produced by"},
  {"title":"frontera:super_crafter usage","url":"uses/frontera_super_crafter.html","text":"frontera:super_crafter usage recipe where used produced by"},
  {"title":"frontera:wooden_carriage_chest usage","url":"uses/frontera_wooden_carriage_chest.html","text":"frontera:wooden_carriage_chest usage recipe where used produced by"},
  {"title":"frontera:wooden_carriage_empty usage","url":"uses/frontera_wooden_carriage_empty.html","text":"frontera:wooden_carriage_empty usage recipe where used produced by"},
  {"title":"frontera:wooden_carriage_hay_bale usage","url":"uses/frontera_wooden_carriage_hay_bale.html","text":"frontera:wooden_carriage_hay_bale usage recipe where used produced by"},
  {"title":"frontera:wooden_wheel usage","url":"uses/frontera_wooden_wheel.html","text":"frontera:wooden_wheel usage recipe where used produced by"},
  {"title":"minecraft:barrel usage","url":"uses/minecraft_barrel.html","text":"minecraft:barrel usage recipe where used produced by"},
  {"title":"minecraft:brick usage","url":"uses/minecraft_brick.html","text":"minecraft:brick usage recipe where used produced by"},
  {"title":"minecraft:bucket usage","url":"uses/minecraft_bucket.html","text":"minecraft:bucket usage recipe where used produced by"},
  {"title":"minecraft:charcoal usage","url":"uses/minecraft_charcoal.html","text":"minecraft:charcoal usage recipe where used produced by"},
  {"title":"minecraft:chest usage","url":"uses/minecraft_chest.html","text":"minecraft:chest usage recipe where used produced by"},
  {"title":"minecraft:clay usage","url":"uses/minecraft_clay.html","text":"minecraft:clay usage recipe where used produced by"},
  {"title":"minecraft:coal usage","url":"uses/minecraft_coal.html","text":"minecraft:coal usage recipe where used produced by"},
  {"title":"minecraft:coal_block usage","url":"uses/minecraft_coal_block.html","text":"minecraft:coal_block usage recipe where used produced by"},
  {"title":"minecraft:cobblestone usage","url":"uses/minecraft_cobblestone.html","text":"minecraft:cobblestone usage recipe where used produced by"},
  {"title":"minecraft:diamond usage","url":"uses/minecraft_diamond.html","text":"minecraft:diamond usage recipe where used produced by"},
  {"title":"minecraft:furnace usage","url":"uses/minecraft_furnace.html","text":"minecraft:furnace usage recipe where used produced by"},
  {"title":"minecraft:gravel usage","url":"uses/minecraft_gravel.html","text":"minecraft:gravel usage recipe where used produced by"},
  {"title":"minecraft:hay_block usage","url":"uses/minecraft_hay_block.html","text":"minecraft:hay_block usage recipe where used produced by"},
  {"title":"minecraft:iron_ingot usage","url":"uses/minecraft_iron_ingot.html","text":"minecraft:iron_ingot usage recipe where used produced by"},
  {"title":"minecraft:iron_nugget usage","url":"uses/minecraft_iron_nugget.html","text":"minecraft:iron_nugget usage recipe where used produced by"},
  {"title":"minecraft:iron_ore usage","url":"uses/minecraft_iron_ore.html","text":"minecraft:iron_ore usage recipe where used produced by"},
  {"title":"minecraft:lava usage","url":"uses/minecraft_lava.html","text":"minecraft:lava usage recipe where used produced by"},
  {"title":"minecraft:lava_bucket usage","url":"uses/minecraft_lava_bucket.html","text":"minecraft:lava_bucket usage recipe where used produced by"},
  {"title":"minecraft:milk usage","url":"uses/minecraft_milk.html","text":"minecraft:milk usage recipe where used produced by"},
  {"title":"minecraft:milk_bucket usage","url":"uses/minecraft_milk_bucket.html","text":"minecraft:milk_bucket usage recipe where used produced by"},
  {"title":"minecraft:oak_log usage","url":"uses/minecraft_oak_log.html","text":"minecraft:oak_log usage recipe where used produced by"},
  {"title":"minecraft:oak_planks usage","url":"uses/minecraft_oak_planks.html","text":"minecraft:oak_planks usage recipe where used produced by"},
  {"title":"minecraft:paper usage","url":"uses/minecraft_paper.html","text":"minecraft:paper usage recipe where used produced by"},
  {"title":"minecraft:stick usage","url":"uses/minecraft_stick.html","text":"minecraft:stick usage recipe where used produced by"},
  {"title":"minecraft:water usage","url":"uses/minecraft_water.html","text":"minecraft:water usage recipe where used produced by"},
  {"title":"minecraft:water_bucket usage","url":"uses/minecraft_water_bucket.html","text":"minecraft:water_bucket usage recipe where used produced by"},
  {"title":"minecraft:wheat usage","url":"uses/minecraft_wheat.html","text":"minecraft:wheat usage recipe where used produced by"},
  {"title":"world:isHighHumidity usage","url":"uses/world_isHighHumidity.html","text":"world:isHighHumidity usage recipe where used produced by"},
  {"title":"world:isRaining usage","url":"uses/world_isRaining.html","text":"world:isRaining usage recipe where used produced by"},
  {"title":"Reverse Lookups","url":"uses/index.html","text":"usage reverse lookup"}
];
